### ISSUE TITLE
Feature request: update to the latest version of Nerd fonts

### ISSUE THREAD

**Issue by nirui** [azurity/pure-nerd-font#1]
Greetings,

Nerd fonts has released it's [version 3] in May, which includes some breaking changes. I wonder if you are interested in updating pure-nerd-font to catch up to the newer ones? Currently, the latest version is [v3.1.1].

That's all, thanks!

[version 3]: https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0
[v3.1.1]: https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.1.1

**Comment by azurity** [comment]
Thanks for your suggestion, version v3.0 has been released corresponding to nerd font v3.1.1

Considering that manual release is still required, if I have time in the future, I will try to write a github action to automatically follow up on the latest version of nerd font.

**Comment by nirui** [comment]
Wow that was fast... you don't really have to give up your sleep for this. But now that's done, thank you again!
